# Generated by Django 4.2.13 on 2024-07-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_alter_event_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('destination_iata', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('origin_iata', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('departure', models.DateField(blank=True, null=True)),
                ('arrival', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
