# Generated by Django 4.2.13 on 2024-07-13 05:46

from django.db import migrations, models
import datetime
from django.utils.timezone import utc

class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now(tz=utc)),
        ),
    ]
