# Generated by Django 4.2.13 on 2024-07-13 05:50

from django.db import migrations
import datetime
from django.utils.timezone import utc

def backfill_created_at(apps, schema_editor):
    Order = apps.get_model('event_manager', 'Order')
    batch_size = 10000
    total_records = Order.objects.count()
    for start in range(0, total_records, batch_size):
        end = start + batch_size
        Order.objects.filter(pk__range=(start, end)).update(created_at=datetime.datetime.now(tz=utc) - datetime.timedelta(days=2))


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_auto_20240713_1046'),
    ]

    operations = [
        migrations.RunPython(backfill_created_at),
    ]
