# Generated by Django 4.2.13 on 2024-07-13 05:53

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_auto_20240713_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=False),
        ),
    ]
